# Generated by Django 4.2.16 on 2025-01-07 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPORTAL', '0009_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='имя категории', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='имя категории', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='имя категории', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPORTAL.author', verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsPORTAL.author', verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsPORTAL.author', verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(through='NewsPORTAL.PostCategory', to='NewsPORTAL.category', verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorys_en_us',
            field=models.ManyToManyField(null=True, through='NewsPORTAL.PostCategory', to='NewsPORTAL.category', verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorys_ru',
            field=models.ManyToManyField(null=True, through='NewsPORTAL.PostCategory', to='NewsPORTAL.category', verbose_name='This is the help text'),
        ),
    ]
