# Generated by Django 4.2.16 on 2025-01-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPORTAL', '0010_alter_author_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPORTAL.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsPORTAL.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsPORTAL.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(through='NewsPORTAL.PostCategory', to='NewsPORTAL.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorys_en_us',
            field=models.ManyToManyField(null=True, through='NewsPORTAL.PostCategory', to='NewsPORTAL.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorys_ru',
            field=models.ManyToManyField(null=True, through='NewsPORTAL.PostCategory', to='NewsPORTAL.category', verbose_name='Category'),
        ),
    ]
