# Generated by Django 4.2.16 on 2025-01-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPORTAL', '0011_alter_post_author_alter_post_author_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
