# Generated by Django 4.2.16 on 2025-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPORTAL', '0012_alter_post_text_alter_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='имя категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(help_text='имя категории', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(help_text='имя категории', null=True),
        ),
    ]
