# Generated by Django 4.2.16 on 2025-01-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPORTAL', '0014_alter_post_text_alter_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorys_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorys_ru',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='category name', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='category name', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='category name', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='NewsPORTAL.category'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='NewsPORTAL.post'),
        ),
        migrations.DeleteModel(
            name='PostCategory_en_us',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
