# Generated by Django 4.2.16 on 2025-01-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPORTAL', '0015_remove_postcategory_ru_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorys',
            new_name='category',
        ),
    ]
