# Generated by Django 4.2.16 on 2025-01-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPORTAL', '0016_rename_categorys_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categorys',
        ),
    ]
